### ISSUE TITLE
Custom component is pulling in the standard HA neato modules

### ISSUE THREAD

**Issue by nathanfaber** [dshokouhi/hass-neato-custom-component#1]
The current code if deployed as a custom_components is still pulling in things like ACTION for the standard module. 

All of the imports for homeassistant.components.vacuum need to be changed to custom_components.neato. 

`sed -i 's/homeassistant.components.neato/custom_components.neato/g' {switch,vacuum,camera}/neato.py
`

After this fix, I am running in my setup and seeing proper updates and action strings.

**Comment by dshokouhi** [comment]
Ah good catch!  Ok think I got it all updated to use the proper import now.  One thing I did get right was making sure the state updates when using a persistent map :)
