### ISSUE TITLE
Prompt for new credentials when the old ones are invalid

### ISSUE THREAD

**Issue by Santobert** [dshokouhi/hass-neato-custom-component#21]
We should ask the user to enter new credentials when the old ones are invalid.

Hue does this here:
https://github.com/home-assistant/home-assistant/blob/b570be47ca253f06e357eea49bbc609012bb87e7/homeassistant/components/hue/bridge.py#L52

Side note: We should only ask for new credentials when there are no credentials saved in configuration.yaml. This should be done here: 
https://github.com/home-assistant/home-assistant/blob/b570be47ca253f06e357eea49bbc609012bb87e7/homeassistant/components/neato/__init__.py#L49

**Comment by Santobert** [comment]
Draft: https://github.com/Santobert/home-assistant/tree/neato_outdated_credentials

**Comment by Santobert** [comment]
@dshokouhi Do you have any idea why this isn't working?
https://github.com/Santobert/home-assistant/blob/2e86c81ecfd316f5f190262c98a74cb2fea1387e/homeassistant/components/neato/config_flow.py#L45

**Comment by dshokouhi** [comment]
I think because it is in `async_step_user` which means its user initiated whereas hue is using `async_create_task`? 

so maybe this needs to live in here? https://github.com/home-assistant/home-assistant/blob/b570be47ca253f06e357eea49bbc609012bb87e7/homeassistant/components/neato/__init__.py#L102

**Comment by Santobert** [comment]
Unfortunately this doesn't work either. Please take a look at my latest commit. That's weird because `async_show_form` gets called...

**Comment by Santobert** [comment]
https://github.com/Santobert/home-assistant/blob/neato_outdated_credentials/homeassistant/components/neato/__init__.py#L102

**Comment by Santobert** [comment]
https://github.com/Santobert/home-assistant/blob/neato_outdated_credentials/homeassistant/components/neato/config_flow.py#L51

**Comment by Santobert** [comment]
no longer important :)
