### ISSUE TITLE
Zone Cleaning

### ISSUE THREAD

**Issue by RomRider** [dshokouhi/hass-neato-custom-component#3]
Hey,

In the `services.yaml` file, you indicate that the boundary_id is mandatory : https://github.com/dshokouhi/hass-neato-custom-component/blob/zone_cleaning/vacuum/services.yaml#L154

Actually, it shouldn't be mandatory as without pybotvac wouldn't fail, it would just use the whole map:
https://github.com/stianaske/pybotvac/blob/master/pybotvac/robot.py#L93-L94

Might just be a `[Required]` to change into `(optionnal)` in the `services.yaml` file though.

However, if you want it to be mandatory, then I think there should be a second service to achieve custom cleaning on the full map, like the one on the `custome_cleaning` branch

Thanks for the great work here!!
I own a D7 and can help/test/develop stuff if needed also.

**Comment by dshokouhi** [comment]
Hey good call, I think that might work better so we have one new service call added.  I will make this change shortly.  Still waiting to see if my PR for adding the zone attributes will pass so I can get ready to submit this.

**Comment by dshokouhi** [comment]
@RomRider it looks like we may not be able to add the zone id to the attributes, so for now I think the next best thing to do is just to use the name that we set in the Neato app and the ID will be grabbed if it matches.  I have updated the zone cleaning branch if you want to give it a run.  Still trying to figure out why we need to send the Name attribute in the service call, may need some help there before I can submit this lol.

**Comment by onkelfarmor** [comment]
Hi,

Updated to the zone cleaning branch, but can't get it to work. Already had the standard Home Assistant Neato component working and I can still see and interact with my Neato from the Home Assistant interface - but tried to make a script, but it won't work (nothing happens when executing):

'1548625318244':
  alias: Hoover in Kitchen
  sequence:
  - data:
      category: 4
      entity_id: vacuum.holger
      mode: 2
      name: Kitchen
      navigation: 1
    service: vacuum.neato_zone_cleaning

Don't know the boundary_id, but as I read, I don't need it. "Kitchen" is the name of the area in the Neato App, tried other areas too. The log gives me an error about "Kitchen":

 neato_zone_cleaning_service
    controller[name].neato_zone_cleaning(mode, navigation, category, zone)
KeyError: 'Kitchen'

**Comment by dshokouhi** [comment]
@onkelfarmor looks the read me was a little out of date, if the name of the zone is "Kitchen" then make sure you send `zone: Kitchen`, for `name` you want the actual name of the botvac from the Neato app.

Here is an example of the service data to send:

```
{"entity_id":"vacuum.mrs_neato",
"mode":2,
"navigation":1,
"category":4,
"zone":"Hallway",
"name":"Mrs. Neato"}
```

**Comment by onkelfarmor** [comment]
@dshokouhi thanks for the answer, but I still cannot get it to work. Get this error now:

`  File "/config/custom_components/vacuum/neato.py", line 67, in neato_zone_cleaning_service
    controller[name].neato_zone_cleaning(mode, navigation, category, zone)
  File "/config/custom_components/vacuum/neato.py", line 259, in neato_zone_cleaning
    for boundary in self._robot_boundaries['data']['boundaries']:
KeyError: 'data'`

My code is like this:

`{
  "category": 4,
  "entity_id": "vacuum.holger",
  "mode": 2,
  "name": "Holger",
  "navigation": 1,
  "zone": "Lounge"
}`

**Comment by dshokouhi** [comment]
@onkelfarmor it looks like there are still issues with what I was trying to implement.  I just reverted back to using the `boundary_id` which is stored in the device attributes.  This version will work.  I have updated the read me with the expected service data as well.

**Comment by onkelfarmor** [comment]
@dshokouhi updated and can now see `boundary_id` in Home Assistant. Zone is changed to the id of one of my zones. When I execute my script, my Neato now starts, but it is very confused and starts hovering just where it starts.

**Comment by dshokouhi** [comment]
@onkelfarmor taht is odd because I just ran 2 separate zone cleaning runs with the same code.  The vacuum starts and scans the room, then it moves on to the zone.  After a few minutes did it eventually clean?  Also is the wifi still connected after it received the command?

**Comment by onkelfarmor** [comment]
@dshokouhi found the error, didn't see that I should change "zone" to "boundary_id", so I just change "Lounge" to my id. Now it works, thanks for the help. Now I can my HomePod to Hoover in Kitchen!

**Comment by RomRider** [comment]
I made it work without the name and with the zone name, please see this commit:
https://github.com/RomRider/home-assistant/commit/c2c830b7c66581df435b46719c128bd95221645a

I'm planning to PR it, unless you prefer to do it yourself, what do you think ?

**Comment by RomRider** [comment]
I've PRed it:
https://github.com/home-assistant/home-assistant/pull/20779

**Comment by dshokouhi** [comment]
@RomRider good job dude :) just gave it a quick review.  Will run this code in my dev later today to play with it.  Next we need to get Config Entries setup :)

**Comment by RomRider** [comment]
@dshokouhi What do you mean by config entries?

**Comment by dshokouhi** [comment]
@RomRider https://developers.home-assistant.io/docs/en/config_entries_index.html its basically where all components are heading to now.  No need for YAML configuration.  Its a requirement for Device Registry which also means that if we want to support Areas and other upcoming HA features we want to update to it.  It just takes more work since we have to write tests for it and I am not that well versed there lol.

**Comment by RomRider** [comment]
I don't like config entries :( it was so nice to have everything in yaml and on git! I hope it will not be the only option in the future...

**Comment by dshokouhi** [comment]
It is just to configure the component, it can be made so it pulls from the configuration.yaml as well so we can still keep it that way :) its just to allow for all the new features really

**Comment by dshokouhi** [comment]
BTW @RomRider are you on discord? maybe we can chat there on improvements and stuff :)

**Comment by dshokouhi** [comment]
closing this issue now that zone cleaning is live, thank you @RomRider for finishing it up :)
