### ISSUE TITLE
Not all zones are listed (multiple floorplans)

### ISSUE THREAD

**Issue by gijbelsy** [dshokouhi/hass-neato-custom-component#4]
I have several zones defined in the Neato app, but HA only shows about half of them at the entities screen.
There is also one attribute of the entity that has no attribute name, only a value (ID-string).

**Comment by gijbelsy** [comment]
Small update on this:
I have multiple floorplans defined. The zone names listed are only the names from the latest created floorplan.

**Comment by dshokouhi** [comment]
@gijbelsy I had a feeling this would come up :) currently this branch is a bit out of date.  There is a current PR in Home Assistant to add zone cleaning but it is based off this repo.

https://github.com/home-assistant/home-assistant/pull/20779

I think that once this PR gets merged we can add in the logic for multiple floorplans.  The new code changes will no longer add attributes to the vacuum, you will be able to call the zone by its name that you set in the Neato app.  I am not sure how well this would work if multiple floorplans had the same name though.  I think this is something we need to think about and consider.

**Comment by gijbelsy** [comment]
Hi @dshokouhi, thanks for the reply.
I'm happy to do some testing if you like.

**Comment by dshokouhi** [comment]
@gijbelsy ok I got something setup to test let me know how it works :)

https://github.com/dshokouhi/hass-neato-custom-component/tree/multiple_floorplans

**Comment by gijbelsy** [comment]
I get the following error in home assistant log:

```
2019-03-08 20:37:09 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.neato.vacuum. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/neato/vacuum.py", line 14, in <module>
    from homeassistant.components.neato import (
ImportError: cannot import name 'NEATO_PERSISTENT_MAPS'
```

**Comment by dshokouhi** [comment]
did you make sure to copy the entire directory and not just the `vacuum.py` file?

**Comment by gijbelsy** [comment]
yes, entire directory, latest update.

**Comment by dshokouhi** [comment]
can you update the `vacuum.py` file with the latest change please

**Comment by gijbelsy** [comment]
Did you just update the file on Git? Because I'm allready running the latest version (downloaded about 15mins ago)

**Comment by dshokouhi** [comment]
yup like 5 min ago :) its just fixing the constants to pull from the custom component folder: https://github.com/dshokouhi/hass-neato-custom-component/blob/multiple_floorplans/neato/vacuum.py#L14

**Comment by gijbelsy** [comment]
ah, OK. For some reason that update wasn't visible to me yet. Must be a caching problem.
I've updated the file and the error is gone.

**Comment by dshokouhi** [comment]
excellent, let  me know if you can clean with zones and different maps :) 

you should be able to pass `zone: <zone_name>` or a full map as `map: <map_name>`

**Comment by dshokouhi** [comment]
it should take any zone from any map too

**Comment by gijbelsy** [comment]
OK, I'll test it.
So as I understand, I don't need the mapID anymore? Just the name is OK?

**Comment by dshokouhi** [comment]
yup the name you have defined in the app (case sensitive) also I saw some users having issues with similar names so if you see the wrong zone running check to see if the name is close to another zone name so try to keep them all unique if you run into that.

**Comment by gijbelsy** [comment]
Understood. I'll run a test tomorrow and keep you updated. Tnx!

**Comment by gijbelsy** [comment]
When calling the vacuum.neato_custom_cleaning service, HomeAssistant replies that it's unable to call the service.
However vacuum.start service, does start the robot.

**Comment by dshokouhi** [comment]
whats the error you got and what attributes did you send?

**Comment by gijbelsy** [comment]
The error was my mistake. Forgot to pass the entity-id.
It's working now. Just did a zone clean, and everything works fine.
Is it possible to add multiple zones to the zone parameter?

**Comment by dshokouhi** [comment]
@gijbelsy no the neato api only allows one zone per cleaning command. 

See the basic-4 section here: https://developers.neatorobotics.com/api/robot-remote-protocol/housecleaning

Glad it is working for you!  So every zone across all floor plans work?  Are you able to clean the entire floor plan of the additional floors too?

**Comment by gijbelsy** [comment]
Didn't test all zones. But I assume the other ones work.
Entire floor is working too. But I need to test this also with the 'map' attribute.
Yesterday I ran a 'floor' test with the vacuum.start service. The robot recognized the floor it was on.

**Comment by dshokouhi** [comment]
Ok as long as you were able to clean a zone from another floor plan other than the first I think it all should work :)

**Comment by dshokouhi** [comment]
Closing as we now find all zones across all floorplans :)
